- name: Update apt cache (Debian)
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install essential packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv
    - python3-pip
    - build-essential
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Python 3 (MacOS)
  homebrew:
    name: python3
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Create virtual environment for macOS
  command: python3 -m venv "{{ project_directory }}/venv"
  args:
    creates: "{{ project_directory }}/venv"
  when: ansible_facts['os_family'] == 'Darwin'

- name: Upgrade pip inside virtual environment (MacOS)
  command: "{{ project_directory }}/venv/bin/pip install --upgrade pip"
  when: ansible_facts['os_family'] == 'Darwin'
