# Generated by Django 4.2 on 2024-11-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('carambus_py', '0005_delete_null_account_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresse',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(related_name='accounts', through='carambus_py.AccountUser', to='carambus_py.user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to='carambus_py.account'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to='carambus_py.user'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='super_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_disciplines', to='carambus_py.discipline'),
        ),
        migrations.AlterField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='version',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['item_type', 'item_id'], name='carambus_py_item_ty_3ba05d_idx'),
        ),
        migrations.AlterModelTable(
            name='version',
            table=None,
        ),
    ]
