# Generated by Django 4.2 on 2024-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carambus_py', '0006_rename_addresse_address_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
