# Generated by Django 4.2 on 2024-11-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carambus_py', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='admin_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_user', to='carambus_py.player'),
        ),
    ]
