# Generated by Django 4.2 on 2024-11-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carambus_py', '0005_rename_addresse_address_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='version',
            table='version',
        ),
    ]
